title: A public test
lang: en
description: Let's see how it works

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
